server:
  port: 8081

spring:
  data:
    arangodb:
      host: localhost
      port: 8529
      username: root
      password: root
      database: pro-01-simple-entity

# Logging DB
#This will also shows query statements as well as other debug messages.
logging.level.com.arangodb: DEBUG